/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyGuideRouteImport } from './routes/survey_.guide'
import { Route as SurveyDoneRouteImport } from './routes/survey_.done'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as JoinCodeRouteImport } from './routes/join_.$code'
import { Route as ClassNewRouteImport } from './routes/class.new'
import { Route as ClassIdRouteImport } from './routes/class.$id'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as CIdRosterRouteImport } from './routes/c.$id_.roster'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyGuideRoute = SurveyGuideRouteImport.update({
  id: '/survey_/guide',
  path: '/survey/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyDoneRoute = SurveyDoneRouteImport.update({
  id: '/survey_/done',
  path: '/survey/done',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join_/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassNewRoute = ClassNewRouteImport.update({
  id: '/class/new',
  path: '/class/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIdRoute = ClassIdRouteImport.update({
  id: '/class/$id',
  path: '/class/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRosterRoute = CIdRosterRouteImport.update({
  id: '/c/$id_/roster',
  path: '/c/$id/roster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/results': typeof ResultsRoute
  '/survey': typeof SurveyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/c/$id': typeof CIdRoute
  '/class/$id': typeof ClassIdRoute
  '/class/new': typeof ClassNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/survey/done': typeof SurveyDoneRoute
  '/survey/guide': typeof SurveyGuideRoute
  '/c/$id/roster': typeof CIdRosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/results': typeof ResultsRoute
  '/survey': typeof SurveyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/c/$id': typeof CIdRoute
  '/class/$id': typeof ClassIdRoute
  '/class/new': typeof ClassNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/survey/done': typeof SurveyDoneRoute
  '/survey/guide': typeof SurveyGuideRoute
  '/c/$id/roster': typeof CIdRosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/results': typeof ResultsRoute
  '/survey': typeof SurveyRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/c/$id': typeof CIdRoute
  '/class/$id': typeof ClassIdRoute
  '/class/new': typeof ClassNewRoute
  '/join_/$code': typeof JoinCodeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/survey_/done': typeof SurveyDoneRoute
  '/survey_/guide': typeof SurveyGuideRoute
  '/c/$id_/roster': typeof CIdRosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/results'
    | '/survey'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/c/$id'
    | '/class/$id'
    | '/class/new'
    | '/join/$code'
    | '/onboarding/role'
    | '/survey/done'
    | '/survey/guide'
    | '/c/$id/roster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/results'
    | '/survey'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/c/$id'
    | '/class/$id'
    | '/class/new'
    | '/join/$code'
    | '/onboarding/role'
    | '/survey/done'
    | '/survey/guide'
    | '/c/$id/roster'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/results'
    | '/survey'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/c/$id'
    | '/class/$id'
    | '/class/new'
    | '/join_/$code'
    | '/onboarding/role'
    | '/survey_/done'
    | '/survey_/guide'
    | '/c/$id_/roster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  ResultsRoute: typeof ResultsRoute
  SurveyRoute: typeof SurveyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CIdRoute: typeof CIdRoute
  ClassIdRoute: typeof ClassIdRoute
  ClassNewRoute: typeof ClassNewRoute
  JoinCodeRoute: typeof JoinCodeRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  SurveyDoneRoute: typeof SurveyDoneRoute
  SurveyGuideRoute: typeof SurveyGuideRoute
  CIdRosterRoute: typeof CIdRosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey_/guide': {
      id: '/survey_/guide'
      path: '/survey/guide'
      fullPath: '/survey/guide'
      preLoaderRoute: typeof SurveyGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey_/done': {
      id: '/survey_/done'
      path: '/survey/done'
      fullPath: '/survey/done'
      preLoaderRoute: typeof SurveyDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join_/$code': {
      id: '/join_/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/new': {
      id: '/class/new'
      path: '/class/new'
      fullPath: '/class/new'
      preLoaderRoute: typeof ClassNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$id': {
      id: '/class/$id'
      path: '/class/$id'
      fullPath: '/class/$id'
      preLoaderRoute: typeof ClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id_/roster': {
      id: '/c/$id_/roster'
      path: '/c/$id/roster'
      fullPath: '/c/$id/roster'
      preLoaderRoute: typeof CIdRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  ResultsRoute: ResultsRoute,
  SurveyRoute: SurveyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CIdRoute: CIdRoute,
  ClassIdRoute: ClassIdRoute,
  ClassNewRoute: ClassNewRoute,
  JoinCodeRoute: JoinCodeRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  SurveyDoneRoute: SurveyDoneRoute,
  SurveyGuideRoute: SurveyGuideRoute,
  CIdRosterRoute: CIdRosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
